### Transpose Vector/Matrix

Setting up enviornment 

In [1]:
# Load library numpy 
#an efficient multi-dimensional container of generic data

import numpy as np 


Create Vector

In [2]:
vector= np.array([3,4,5,1,2,3,6,7,8])

Create Matrix

In [8]:
matrix= np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Transpose Vector 

In [6]:
vector.T

array([3, 4, 5, 1, 2, 3, 6, 7, 8])

Transpose Matrix 

In [7]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])